import Head from 'next/head';
import React from 'react';
import { Navbar } from '../Navbar';
import styles from './MainLayout.module.css';

interface Props {
  children: React.ReactNode;
}

export const MainlLayout = ({ children }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Edgard Alas</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className={styles.main}>{children}</main>
    </div>
  );
};
